// <auto-generated />
namespace NewPDR.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PDRStatusColm1Seed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PDRStatusColm1Seed));
        
        string IMigrationMetadata.Id
        {
            get { return "201604070902388_PDRStatusColm1Seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
